container:
  image: cirrusci/android-sdk:28
  cpu: 4
  memory: 8G

task:
  name: tests
  script: ./gradlew test

task:
  name: debug-build

  depends_on:
    - tests

  build_release_apk_script: |
    ./gradlew assembleDebug

  output_artifacts:
    path: "./app/build/outputs/apk/debug/*.apk"
