sudo: false
language: android
jdk: oraclejdk8

env:
  global:
    # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
    # via the "travis encrypt" command using the project repo's public key
     - secure: "DYDhuyhpMawWuS7OafFxddAWlYPQoWgjW3QWgLY9DOPFQmM1OC1psVnNcy8dqnKYEa5LWwbEdhRlqDCWb+M5iDEtC4cCWVT+pj65It26eekaAh2axSife7eHMJNyXqU5KJ12fFmvc/wQvY1Z7gooEDuDTcDVYw5DrI09FHN0SB8xGZiTjBtcXHOK9QvAqsZTuLmaflbl00S0Fwh0ddQosXX0C9DbUs2pepWviS5LsDWK3R68QXlU5VOHa4//tBC2wDZWyC+R+pF4yTnj+kwFo/dY3JeY0t8iXS4YOnYhxldZoM/zGzuUH8XGV2BaMGSLLUgJvMziHFnCBAs5I3x3gWIc4NNMqQv4KmQ9d3t1GORot+Bff5puLV7HSMaQ2SpodUpLkF3AJhjm+piNLE1LW8qU+sAMemC2K+FcsohmizMm2spMgy9I9mjFxtlFOhDW+s+TcPefVWTVTlrkGAVxd/bbM1HSRz3Xkr2jAdMcYO0PeEcp9v+ups2sIND+RWU0HJ+IdC7ofL1BcCW61a2g2voAB17Az2wPtZ77taz12G/dhXw8VbOynd/qKzdUKOHpxkWlhP/KioFisgCq1LCvR8WqTs/fHF15VoCPzI/BdNi2Pb3t76US5pVMBrB4Dg5YNUxEoDP+Yin6etdo6bnPsUQE+uc9bFHd3Me9h5Z11hM="

android:
  components:
    - platform-tools
    - tools
    - build-tools-25.0.2
    - android-25
    - extra-android-m2repository

before_install:
  - git clone https://github.com/urho3d/android-ndk.git $HOME/android-ndk
  - export ANDROID_NDK_HOME=$HOME/android-ndk

script:
  - ./gradlew testDebugUnitTest

addons:
  coverity_scan:
    project:
      name: "termux/termux-app"
      description: "Terminal emulator and Linux environment for Android"
    notification_email: fredrik@fornwall.net
    build_command_prepend: "./gradlew clean"
    build_command: "./gradlew build"
    branch_pattern: master
